services:
  app:
    build:
      context: .
    container_name: user_service
    ports:
      - "8083:8083"
    depends_on:
      - db-news
    restart: always
  db-news:
    image: postgres:15
    environment:
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: news_pass
      POSTGRES_DB: USER_PLATFORM
    ports:
      - "5435:5432"