spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/USER_PLATFORM
    username: news_user
    password: news_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true